deployment:
  phases:
    install:
      - cd ./client && npm install --production
      - cd ./server && npm install --production

#     build:
#       - cd ./client && npm run build
#       - cd ./server && npm run build

#     deploy:
#       - cp -R ./client/dist /home/ficl4036/public_html/projet3/
#       - cp -R ./server/dist /home/ficl4036/public_html/projet3-api/
