---
deployment:
  tasks:
      - rm package.json
      - rm package-lock.json

      - export PATH="$PATH:/opt/alt/alt-nodejs20/root/usr/bin/"

      - cd ./client && npm install
      - cd ..
      - cd ./server && npm install
      - cd ..

      - cd ./client && npm run build
      - cd ..
      - cd ./server && npm run build
      - cd ..

      - mkdir -p /home/ficl4036/public_html/projet3
      - mkdir -p /home/ficl4036/public_html/projet3-api

      - cp -R ./client/dist/* /home/ficl4036/public_html/projet3/
      - cp -R ./server/dist/* /home/ficl4036/public_html/projet3-api/
